name: Rust

on:
  pull_request:
  push:
    branches: [main]
  release: [published]

env:
  RUSTFLAGS: -D warnings

jobs:

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable && rustup default stable
    - run: cargo fmt --check

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable && rustup default stable
    - run: cargo build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable && rustup default stable
    - run: cargo test

  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update nightly && rustup default nightly
    - run: cargo bench

  publish:
    if: github.event_name == 'release'
    needs: [fmt, build, test, bench]
    runs-on: ubunut-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable && rustup default stable
    - run: cargo publish
